export const NFTCardsInfo = [
  {
    nftImage: "https://picsum.photos/1000",
    nftTitle: "NFT Foda",
    nftUser: "RukasuArumada",
    nftUserImage: "https://picsum.photos/20",
    nftPrice: "3.14",
    nftHighest: "5.00",
    bgColor: "#2B2B2B",
  },
  {
    nftImage: "https://picsum.photos/1000",
    nftTitle: "NFT Foda 2",
    nftUser: "LucasMamada",
    nftUserImage: "https://picsum.photos/20",
    nftPrice: "102.45",
    nftHighest: "103.00",
    bgColor: "#2B2B2B",
  },
  {
    nftImage: "https://picsum.photos/1000",
    nftTitle: "NFT Foda 2",
    nftUser: "LucasMamada",
    nftUserImage: "https://picsum.photos/20",
    nftPrice: "102.45",
    nftHighest: "103.00",
    bgColor: "#2B2B2B",
  },
  {
    nftImage: "https://picsum.photos/1000",
    nftTitle: "NFT Foda 2",
    nftUser: "LucasMamada",
    nftUserImage: "https://picsum.photos/20",
    nftPrice: "102.45",
    nftHighest: "103.00",
    bgColor: "#2B2B2B",
  },
  {
    nftImage: "https://picsum.photos/1000",
    nftTitle: "NFT Foda 2",
    nftUser: "LucasMamada",
    nftUserImage: "https://picsum.photos/20",
    nftPrice: "102.45",
    nftHighest: "103.00",
    bgColor: "#2B2B2B",
  },
  {
    nftImage: "https://picsum.photos/1000",
    nftTitle: "NFT Foda 2",
    nftUser: "LucasMamada",
    nftUserImage: "https://picsum.photos/20",
    nftPrice: "102.45",
    nftHighest: "103.00",
    bgColor: "#2B2B2B",
  },
  {
    nftImage: "https://picsum.photos/1000",
    nftTitle: "NFT Foda 2",
    nftUser: "LucasMamada",
    nftUserImage: "https://picsum.photos/20",
    nftPrice: "102.45",
    nftHighest: "103.00",
    bgColor: "#2B2B2B",
  },
  {
    nftImage: "https://picsum.photos/1000",
    nftTitle: "NFT Foda 2",
    nftUser: "LucasMamada",
    nftUserImage: "https://picsum.photos/20",
    nftPrice: "102.45",
    nftHighest: "103.00",
    bgColor: "#2B2B2B",
  },
  {
    nftImage: "https://picsum.photos/1000",
    nftTitle: "NFT Foda 2",
    nftUser: "LucasMamada",
    nftUserImage: "https://picsum.photos/20",
    nftPrice: "102.45",
    nftHighest: "103.00",
    bgColor: "#2B2B2B",
  },
];
